apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:58uXpUufoWUpKuZ+y4UwmhB2heWoGzqa8wdK062bWGo8w4ItY5lLgHE+9OxJoKJ6SeR7kt8ogU7UbN6SHKg7nzENYUQx/pOoBB7EgLeHpL8BgLD4ZWSWlUDgctcRVP8Aiu/6aqa8vSzUTm7pfffXEZzcDWuLmoI9CSWiLU+THi6a55i/TAxQ3HKI38OowC6T2twyd88mf8lz+K5+y/SPdYA9DNVZ3HeBxLoIdcGdzaH2IgaUsR+XNdy0ULxoe0/ExARKXlFQODdMxxO+G8UtplLo1qDcP34eCJF1BtF7jXkjWncj8PlHnY0NRNgYgSFhReS0WRMogfWlh/MgreXpMNVCw+mdxM+tOgrTuROLaGn4zehNushGvoQFP/N9pmt9,iv:vLyrIOzcq8IdHzONHugvtTBoV0Oz1Fz/RIAKupKec8o=,tag:2QLS6v0t93MNBVjWSjE+jQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:PsAGKLG3LQeJZMoJ6fQw54iOpxvXB/4lKk+vCgIpLchAu9dw0KEqZRCig3AFUbLLypjy6IkqwxODIt4/MKMoLtaII30jMxV/zNGdeX99J6v30YdssqZSg/ROZScqaMEq+y/tWuFvQhoBufK+1WBheIhoRKzS1MHa6WJAYOIL8XTo0N4kGX6VhhQY54deDQdefZZnzrhvWxTr+8/+ZBILCPhy7apJ4GG8h6mlppzc6uS2Awg/fqyyfDmge3Tm+97q2dUq5KsROd4MKVzMOQ==,iv:0V/+8DPD68A2hkYXR48/OPMLclKlkUJNtSnSxiJ+hwI=,tag:OkCilILBikCIUO27icDOcQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:970UzF2B0MwRlw1dpZQRBTqk/4qnecrZGCd5jm3v2Uf4XiuG+qxzaKgRpldygfKBBQNMuiAcEfnYdMDn3KWy5NDhZc6kqSklCEd+KRK4u11mo1au6Ufm/W+q0rvXIlokWF1o+bdrDXevIROWnjr+reG1A/kXpw0R44IAX2y/zXHCV2PXl5s/mXzvbXpjMS7+D56tMVMqfLC5NgTvhFgYXO2PubrxdobwfDG/,iv:WQfe/YgM7NpbtoZECwjv0PE0mVqNGuGDPkLt8hkLTxQ=,tag:hc1t3v/4PzMOlV7MCOrLdg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12axgaaqe07mdy7jp8hvnhgd42pqr6dq6vwwc9z7r0dmsd0m9he6qntdqwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRnQzWkp1MmpTa0RJR2p0
            OERHUHF1V0tzMmt1UXk1YmwvdDUrTDBnV1RnCmpQOHJpMFB3Z2lSSkpEV3E2ZWt1
            a1V4NDhkdGNFV1FNNUFlY0trR1BqS2sKLS0tIFIwNmNOVE1CVGR3YTRQUUJpS2o1
            TC9Qc3BNOWJjbS9KcmtEMXR0TVUxdEkKTpsRnAkTj7YbW6IlJQa5OesGVIUYHU40
            kyUv0xRL5Xtx7V6NSw/l67IfnXTX80iaB/osqd4utmNGI4ujy4Sozw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T20:20:38Z"
    mac: ENC[AES256_GCM,data:S1OQiFhG9vopMpeB7gsJwsOjEF1NOO6q3r50OV3LQ31J/ESk6Sr9V+7JYUAVTUrW49J1bkQO/xOItuQwjzZvS64INFeXnq6I7eB/kTyXWTs/cCSMIXuH5c0XQMLTTku5FNgHHwSCq6RwcFMn12yqw0uPjnhIyNdWIraIf2JgkwY=,iv:Goc2dO/TJywja3FKpECIi/eEE/6dV/3qhe3Se774sJ4=,tag:oI50iAbV9DKzR0d6hk68Jw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
