apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:H7BligSZJwaaXctVXS9cji9GdMWsIJPvDN2NJ2WXSrGWBJc11zpCdAKMxeNnWycE29M1NO2a4Ocb/qLR7TPqOvHZTvTjxseo4Y68qFEksAZeffow86R3DClwtax+nyZaJ7e2l2n59EsPolHKtzbjCMRY6aX6ItmhvIunOeCzwgkuqkcLnV9gOWoEOZo7nLHOQXDroxTWkg87IJ4qcdNZJjVt7yRE4YKzv3L8vjOGtb6xoxHqbVQUO+r6eCu+ptYGcJY1weyXsqkl2BACJHPKhtZAKpx+FB8z9BS8B6bU3N48RGU5o4mMVNzNmFELuHbdv/C0asTV2dhQn4JpQ9iQLxcugWkUO9Ou2drtvDJvlR7zsnt5ivUQsWcY4pQG5OtV,iv:lm+4hyRi7fRrDFChOJOIJWK3j/9H2BgrMaV4p5OmK30=,tag:WYvzlauWfslTNDAMhpMK0w==,type:str]
    identity.pub: ENC[AES256_GCM,data:glZUxv6visv0M+wjiPgelFWJHIUBzPN29aedzjQSqWJU94iRbzlaflUwLz7MLrWHsY89dITQmAyzm+Anleqsm+RP9eR2sZ5ivK/O3kF7ivzxy7oGveXG/6hYQcV/QDWUYfgvOFapBWqs74xtKVgklwclEMEYD5ssGoSETikgqqZyCHpD96kg3aV5n3T2p8bxFnJ17g5jxjYT/LB7OTsoRWsOXRkvWcLWOPobohYd82IF6+IRWbnp1dmewtD4su6aC5/ra7UdeNxu+poi/w==,iv:2vQgJrE8/OEAkAml6aAfg6bOiw5+dmdd6hBMybC8hXI=,tag:p1r3NF39/go7gvpWp6CxGA==,type:str]
    known_hosts: ENC[AES256_GCM,data:x7oO8HrVTqGohWyGXmu42oMEF2SZVjHcOd/YJtT7wtBQdEjjQ5ps/6qmy7fenrPTEAyAnrY7x+uitcQ0Qc7EQjVo1hHWZZ3hLEcB5E/9w8ITBVRYe1cyPRImth41FcrfebvlMVA4VMAEBSo0eMkGTWcFRMdTkCIH1udu0nCcCn3bX3Kd4N1/wp/UUORihS5wVAHl3Trg90KaWFSfFVhRpaRJdg9X8cIOUJWT,iv:uGRE5zwbgOhvfp2h6UOrByjLGWgKC8a2RGSR2BNDQf8=,tag:dEsS+3SRhFCGsoOFi4n0mQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12axgaaqe07mdy7jp8hvnhgd42pqr6dq6vwwc9z7r0dmsd0m9he6qntdqwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNm1ZZTk0UkJqSEc5Q3FC
            dEwzamdOUkNLclJRT2U1OVAzM2piR2NLZjNJClluczd4d0RBYzM4UjlvNnBYcUVQ
            KzFlU25wNzBNYmJDNE1Vc2VrMmZSVDgKLS0tIFdLVnFiWFFqaWZHSTlWUUNFWXNR
            WDFWK2RBMWkyVHdwbG5jRVhTcGhuWXMKKAji5wcB27u0ivUNHAlSVOPplrZg6RBn
            wSo5mVXGefK2OeZ21RYQCuR7/rfCI9bD//WX7t31rJs5bkrkJ+BAcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T12:49:53Z"
    mac: ENC[AES256_GCM,data:urPTQtehxfd6ZIn40diAWXkGwtHohX3hPcjxTJmCE1LYunzSmZCfor+VlGi+kegbZxE2LUXczlvJIFFAVKyFwwlimiUEWEQ8nwiEdgHQ9v0bVgCIdUovostzJMs2B6zCDjHW4rJET6nXMbp+Nq7C5euL40Azc/aLEyKJo6Yck3o=,iv:HoY1xVwsmFSUxB12OVT5hNwhL1j20qZt66sI+y0LaqM=,tag:POOo1EeSXw81Vc7GfKxLDA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.2
